### ISSUE TITLE
Polar Cloud

### ISSUE THREAD

**Issue by benAsher** [OctoPrint/plugins.octoprint.org#118]
Hi I can't install a plug-in. there is a mistake. As to correct it
[octoprint.log](https://github.com/OctoPrint/plugins.octoprint.org/files/1364722/octoprint.log)

Log

2017-10-07 18:01:15,830 - octoprint.plugins.discovery - INFO - pybonjour is not installed, Zeroconf Discovery won't be available
2017-10-07 18:01:15,842 - octoprint.plugin.core - INFO - Found 12 plugin(s) providing 11 mixin implementations, 11 hook handlers
2017-10-07 18:01:15,915 - octoprint.plugin.core - INFO - Loading plugins from /home/octoprint/OctoPrint/venv/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/plugins, /home/octoprint/.octoprint/plugins and installed plugin packages...
2017-10-07 18:01:16,290 - octoprint.plugin.core - INFO - Found 12 plugin(s) providing 11 mixin implementations, 11 hook handlers
2017-10-07 18:01:16,343 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/octoprint/.octoprint/uploads...
2017-10-07 18:01:16,432 - octoprint.filemanager.storage - INFO - ... file metadata for /home/octoprint/.octoprint/uploads initialized successfully.
2017-10-07 18:01:16,600 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2017-10-07 18:01:20,826 - octoprint.util.pip - INFO - Using "/home/octoprint/OctoPrint/venv/bin/python -m pip" as command to invoke pip
2017-10-07 18:01:24,708 - octoprint.util.pip - INFO - Version of pip is 9.0.1
2017-10-07 18:01:24,710 - octoprint.util.pip - INFO - pip installs to /home/octoprint/OctoPrint/venv/lib/python2.7/site-packages, --user flag needed => no, virtual env => yes
2017-10-07 18:01:24,715 - octoprint.plugin.core - INFO - Initialized 11 plugin implementation(s)
2017-10-07 18:01:24,730 - octoprint.plugin.core - INFO - 12 plugin(s) registered with the system:
|  Announcement Plugin (bundled) = /home/octoprint/OctoPrint/venv/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/plugins/announcements
|  BLTouch Plugin (0.2.0) = /home/octoprint/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_BLTouch
|  Core Wizard (bundled) = /home/octoprint/OctoPrint/venv/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/plugins/corewizard
|  Cost Estimation (2.0.0) = /home/octoprint/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_costestimation
| !CuraEngine (<= 15.04) (bundled) = /home/octoprint/OctoPrint/venv/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/plugins/cura
|  Discovery (bundled) = /home/octoprint/OctoPrint/venv/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/plugins/discovery
|  Filament Manager (0.2.2) = /home/octoprint/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_filamentmanager
|  Plugin Manager (bundled) = /home/octoprint/OctoPrint/venv/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/plugins/pluginmanager
|  Print History Plugin (1.2) = /home/octoprint/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_printhistory
|  Printer Stats (1.0.0) = /home/octoprint/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_stats
|  Software Update (bundled) = /home/octoprint/OctoPrint/venv/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/plugins/softwareupdate
|  Virtual Printer (bundled) = /home/octoprint/OctoPrint/venv/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/plugins/virtual_printer
2017-10-07 18:01:24,732 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2017-10-07 18:01:24,746 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2017-10-07 18:01:24,752 - octoprint.server - INFO - Reset webasset folder /home/octoprint/.octoprint/generated/webassets...
2017-10-07 18:01:24,786 - octoprint.server - INFO - Reset webasset folder /home/octoprint/.octoprint/generated/.webassets-cache...
2017-10-07 18:01:25,645 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance on DietPi for SSDP
2017-10-07 18:01:25,667 - octoprint.server - INFO - Listening on http://0.0.0.0:5000
2017-10-07 18:01:25,738 - octoprint.plugins.stats - INFO - Printer Stats
2017-10-07 18:01:25,887 - octoprint.server.preemptive_cache - INFO - Preemptively caching / (ui _default) for {'query_string': 'l10n=en', 'path': '/', 'base_url': 'http://192.168.1.45:5000/'}
2017-10-07 18:01:31,052 - octoprint.util.pip - INFO - Using "/home/octoprint/OctoPrint/venv/bin/python -m pip" as command to invoke pip
2017-10-07 18:01:31,055 - octoprint.util.pip - INFO - Version of pip is 9.0.1
2017-10-07 18:01:33,288 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from http://plugins.octoprint.org/
2017-10-07 18:01:33,602 - octoprint.plugins.announcements - INFO - Loaded channel _important from http://octoprint.org/feeds/important.xml in 7.9s
2017-10-07 18:01:39,127 - octoprint.util.pip - INFO - pip installs to /home/octoprint/OctoPrint/venv/lib/python2.7/site-packages/, --user flag needed => no, virtual env => yes
2017-10-07 18:01:39,247 - octoprint.plugins.announcements - INFO - Loaded channel _blog from http://octoprint.org/feeds/octoblog.xml in 4.5s
2017-10-07 18:01:39,843 - octoprint.plugins.announcements - INFO - Loaded channel _plugins from http://plugins.octoprint.org/feed.xml in 0.47s
2017-10-07 18:01:41,086 - octoprint.plugins.announcements - INFO - Loaded channel _octopi from http://octoprint.org/feeds/octopi.xml in 1.1s
2017-10-07 18:01:42,258 - octoprint.server.preemptive_cache - INFO - ... done in 16.37s
2017-10-07 18:01:46,770 - octoprint.plugins.softwareupdate - INFO - Saved version cache to disk
2017-10-07 18:02:07,843 - octoprint.server.util.sockjs - INFO - New connection from client: 192.168.1.167
2017-10-07 18:08:01,036 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from http://plugins.octoprint.org/
2017-10-07 18:08:01,049 - octoprint - ERROR - Exception on /api/plugin/pluginmanager [GET]
Traceback (most recent call last):
  File "/home/octoprint/OctoPrint/venv/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/octoprint/OctoPrint/venv/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/octoprint/OctoPrint/venv/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/octoprint/OctoPrint/venv/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/octoprint/OctoPrint/venv/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/octoprint/OctoPrint/venv/local/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/server/api/__init__.py", line 68, in pluginData
    response = api_plugin.on_api_get(request)
  File "/home/octoprint/OctoPrint/venv/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/plugins/pluginmanager/__init__.py", line 216, in on_api_get
    self._repository_available = self._refresh_repository()
  File "/home/octoprint/OctoPrint/venv/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/plugins/pluginmanager/__init__.py", line 706, in _refresh_repository
    repo_data = self._fetch_repository_from_url()
  File "/home/octoprint/OctoPrint/venv/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/plugins/pluginmanager/__init__.py", line 693, in _fetch_repository_from_url
    repo_data = r.json()
  File "/home/octoprint/OctoPrint/venv/local/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/models.py", line 819, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
2017-10-07 18:08:01,073 - tornado.access - ERROR - 500 GET /api/plugin/pluginmanager?refresh_repository=true (192.168.1.167) 310.53ms
2017-10-07 18:09:43,132 - octoprint.plugins.pluginmanager - INFO - Installing plugin from https://github.com/markwal/OctoPrint-PolarCloud
2017-10-07 18:09:52,433 - octoprint.plugins.pluginmanager - ERROR - Installing the plugin from https://github.com/markwal/OctoPrint-PolarCloud failed, could not parse output from pip. See plugin_pluginmanager_console.log for generated output
2017-10-07 18:10:31,070 - octoprint.plugins.pluginmanager - INFO - Installing plugin from /tmp/tmpossfAB.zip
2017-10-07 18:11:53,737 - octoprint.plugins.pluginmanager - ERROR - Installing the plugin from /tmp/tmpossfAB.zip failed, could not parse output from pip. See plugin_pluginmanager_console.log for generated output

**Comment by foosel** [comment]
```
2017-10-07 18:08:01,036 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from http://plugins.octoprint.org/
2017-10-07 18:08:01,049 - octoprint - ERROR - Exception on /api/plugin/pluginmanager [GET]
ValueError: No JSON object could be decoded
```

You misconfigured your plugin manager, it doesn't fetch from the repository feed but instead the website (which doesn't work). Make sure Settings > Plugin Manager > Wrench Icon looks like this, with `http://plugins.octoprint.org/plugins.json` (NOT just `http://plugins.octoprint.org`):

![image](https://user-images.githubusercontent.com/83657/31309643-ce5f3d30-ab89-11e7-8c76-e55dbffedc55.png)

And then you tried to install manually, but used the plugin's repository URL instead of the actual plugin archive URL:

```
2017-10-07 18:09:43,132 - octoprint.plugins.pluginmanager - INFO - Installing plugin from https://github.com/markwal/OctoPrint-PolarCloud
```

The help on plugins.octoprint.org that is linked from every plugin page's "Installation" box explains how to manually install a plugin from archive, see the second option [here](http://plugins.octoprint.org/help/installation/).

However, if you configure your plugin manager's repository URL correctly as explained at the start of this comment, you can just install from the repository listing therein instead.
